version: "3"
services:
  mpt:
    container_name: mpt
    image: amazoncorretto:21
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - 'C:\Users\maks\ks\pr5\bots\bot:/mpt'
    command: java -Dfile.encoding=utf-8 -jar /mpt/VKBot.jar
  palworld:
    image: thijsvanloef/palworld-server-docker:latest
    restart: unless-stopped
    container_name: PalWorld
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    environment:
        - PUID=1000
        - PGID=1000
        - PORT=8211 # Optional but recommended
        - PLAYERS=16 # Optional but recommended
        - SERVER_PASSWORD="mas" # Optional but recommended
        - MULTITHREADING=true
        - RCON_ENABLED=true
        - RCON_PORT=25575
        - TZ=UTC
        - ADMIN_PASSWORD="password"
        - COMMUNITY=false  # Enable this if you want your server to show up in the community servers tab, USE WITH SERVER_PASSWORD!
        - SERVER_NAME="server"
    volumes:
        - ./palworld:/palworld/
  satisfactory-server:
      container_name: 'satisfactory-server'
      hostname: 'kissota.ru'
      image: 'wolveix/satisfactory-server:latest'
      ports:
          - '7777:7777/udp'
          - '15000:15000/udp'
          - '15777:15777/udp'
      volumes:
          - '/root/satisfactory/config:/config'
      environment:
          - MAXPLAYERS=4
          - PGID=1000
          - PUID=1000
          - ROOTLESS=false
          - STEAMBETA=false
      restart: always
      deploy:
        resources:
          limits:
            memory: 6G
          reservations:
            memory: 4G

volumes:
  mpt: