version: '3.3'
services:
  ngnix:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - myapp:/usr/share/nginx/html
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
volumes:
  myapp: